package at.tatami.club.domain.usecase

import at.tatami.auth.domain.usecase.GetCurrentUserUseCase
import at.tatami.domain.model.Club
import at.tatami.domain.repository.ClubRepository
import at.tatami.person.domain.usecase.GetSelectedPersonUseCase
import kotlin.time.ExperimentalTime

class CreateClubUseCase(
    private val clubRepository: ClubRepository,
    private val getCurrentUserUseCase: GetCurrentUserUseCase,
    private val getSelectedPersonUseCase: GetSelectedPersonUseCase
) {
    @OptIn(ExperimentalTime::class)
    suspend operator fun invoke(name: String): Result<Club> {
        return try {
            val currentUser = getCurrentUserUseCase()
                ?: return Result.failure(Exception("User not authenticated"))

            val selectedPerson = getSelectedPersonUseCase.awaitSelectedPerson()
                ?: return Result.failure(Exception("No person selected"))
            val selectedPersonId = selectedPerson.id

            val club = Club(
                id = "", // Will be generated by Firestore
                name = name.trim(),
                clubImgUrl = null,
                ownerId = selectedPersonId, // Owner is the selected person, not the user
                adminIds = listOf(selectedPersonId), // Creator person is automatically an admin
                memberIds = listOf(selectedPersonId), // Creator is the first member
                inviteCode = "" // Will be generated later by cloud function if needed
            )

            // Create club directly in Firestore - security rules will validate
            val createdClub = clubRepository.createClub(club)

            Result.success(createdClub)
        } catch (e: Exception) {
            Result.failure(e)
        }
    }
}