package at.tatami.training.domain.usecase

import at.tatami.club.domain.usecase.GetSelectedClubUseCase
import at.tatami.domain.model.Training
import at.tatami.domain.repository.TrainingRepository
import kotlinx.datetime.LocalDateTime

/**
 * Creates a new training session for a group.
 * The training is created with empty notes and no attendees initially.
 *
 * @param trainingRepository Repository for training data access
 * @param getSelectedClubUseCase Use case to get the currently selected club
 */
class CreateTrainingUseCase(
    private val trainingRepository: TrainingRepository,
    private val getSelectedClubUseCase: GetSelectedClubUseCase
) {
    /**
     * Creates a training session.
     * @param groupId The ID of the group this training is for
     * @param startDateTime When the training session starts
     * @return Result with created Training or failure
     */
    suspend operator fun invoke(
        groupId: String,
        startDateTime: LocalDateTime
    ): Result<Training> {
        return try {
            val selectedClub = getSelectedClubUseCase()
                ?: return Result.failure(Exception("No club selected"))

            val training = Training(
                id = "", // Will be generated by Firestore
                clubId = selectedClub.id,
                groupId = groupId,
                startDateTime = startDateTime,
                notes = "",
                attendedPersonIds = emptyList()
            )

            val createdTraining = trainingRepository.createTraining(training)
            Result.success(createdTraining)
        } catch (e: Exception) {
            Result.failure(e)
        }
    }
}