package at.tatami.person.domain.usecase

import at.tatami.auth.domain.usecase.GetCurrentUserUseCase
import at.tatami.domain.model.Sex
import at.tatami.domain.model.Person
import at.tatami.domain.repository.PersonRepository

class CreatePersonUseCase(
    private val personRepository: PersonRepository,
    private val getCurrentUserUseCase: GetCurrentUserUseCase
) {
    suspend operator fun invoke(
        firstName: String,
        lastName: String,
        yearOfBirth: Int,
        sex: Sex
    ): Result<Person> {
        return try {
            val currentUser = getCurrentUserUseCase()
                ?: return Result.failure(Exception("User not authenticated"))

            val person = Person(
                id = "", // Will be generated by Firestore
                userId = currentUser.id,
                firstName = firstName.trim(),
                lastName = lastName.trim(),
                yearOfBirth = yearOfBirth,
                sex = sex,
                personImgUrl = null,
                clubIds = emptyList()
            )

            // Create person directly in Firestore - security rules will validate
            val createdPerson = personRepository.createPerson(person)

            Result.success(createdPerson)
        } catch (e: Exception) {
            Result.failure(e)
        }
    }
}